version: 2.1

jobs:
  build:
    macos:
      xcode: "15.4.0"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      # Checkout the project
      - checkout

      # Install CocoaPods dependencies
      - run:
          name: Install CocoaPods Dependencies
          command: |
            gem install cocoapods --user-install
            pod install

      # Build the app
      - run:
          name: Build the App
          command: |
            xcodebuild -workspace CircleCi.xcworkspace \
              -scheme CircleCi \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.2' \
              clean build

      # Run Unit Tests
      - run:
          name: Run Unit Tests
          command: |
            xcodebuild test -workspace CircleCi.xcworkspace \
              -scheme CircleCi \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.2'

      # Run UI Tests (if applicable)
      - run:
          name: Run UI Tests
          command: |
            xcodebuild test -workspace CircleCi.xcworkspace \
              -scheme CircleCiUITests \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.2'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
