version: 2.1

jobs:
  build:
    macos:
      xcode: "15.4”  # Use the Xcode version compatible with your project
    working_directory: ~/project
    steps:
      - checkout  # Pull the code from the repository

      - run:
          name: Build the Project
          command: |
            xcodebuild build \
            -project CircleCi.xcodeproj \
            -scheme CircleCi \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
